### ISSUE TITLE
zipping error

### ISSUE THREAD

**Issue by eric-xw** [Cloud-CV/EvalAI-Starters#12]
I encountered the following error when running `./run.sh`

```
zip warning:   first full name: evaluation_script/__init__.py
                      second full name: evaluation_script/pycocotools/__init__.py
                     name in zip file repeated: __init__.py
                     this may be a result of using -j
zip error: Invalid command arguments (cannot repeat names in zip file)
```

Is `-j` necessary? If so, how can we fix it if we have multiple ` __init__.py` under different sub-directories? Thanks!

**Comment by KhalidRmb** [comment]
Hey, @eric-xw ! Thanks for bringing this to our notice. For now you can replace line 9 in `run.sh` with this: `cd evaluation_script && zip -r ../evaluation_script.zip .  -x "*.DS_Store" && cd ..`.

**Comment by eric-xw** [comment]
Hi @KhalidRmb, thanks for your quick response.

I followed the instruction but face another issue now: 
after I submitted the zip file to the EvalAI server, I tested it by submitting an example file; however, the status is always `submitted` and the other statuses are all none.  
```
Stdout File | Stderr File | Result File | Metadata File
-- | -- | -- | --
```

**Comment by eric-xw** [comment]
it was because no evaluation can be run until it is approved. it takes time to be approved, so probably just be patient.
