### ISSUE TITLE
What is the correct way to insert an image in description?

### ISSUE THREAD

**Issue by zhxgj** [Cloud-CV/EvalAI-Starters#20]
I have the following html code to insert an image in description.html. The image is in the same directory as description.html. But the image does not show up in the evalai website of the competition.

`<img width="100%" src="example.png" alt="Example">`

**Comment by RishabhJain2018** [comment]
Hi @zhxgj, 

The `src` must be the path of an image uploaded on a server and image should be publically accessible. 
Please let me know if you have more questions.

**Comment by zhxgj** [comment]
Thank you for your help @RishabhJain2018 This method works with me.
